---
- name: configuration check
  block:
    - name: check monit configuration
      command: monit -t
      ignore_errors: true
      register: monit_syntax_check
      changed_when: false

    - name: show errors
      debug:
        msg: "{{ monit_syntax_check.stderr }}"
      when: monit_syntax_check.rc != 0

    - name: Notify if bad syntax
      assert:
        that:
          - monit_syntax_check.rc == 0
        fail_msg: "Monit configuration check failed. You should check debug information above and fix the problem(s)."

    - name: monit reload
      service:
        name: monit
        state: reloaded
        enabled: yes
      when: monit_syntax_check.rc == 0
  when: not ansible_check_mode
